// Generated by gencpp from file lane_follower/LaneDetection.msg
// DO NOT EDIT!


#ifndef LANE_FOLLOWER_MESSAGE_LANEDETECTION_H
#define LANE_FOLLOWER_MESSAGE_LANEDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lane_follower
{
template <class ContainerAllocator>
struct LaneDetection_
{
  typedef LaneDetection_<ContainerAllocator> Type;

  LaneDetection_()
    : header()
    , offset(0.0)
    , left_lane_detected(false)
    , right_lane_detected(false)  {
    }
  LaneDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , offset(0.0)
    , left_lane_detected(false)
    , right_lane_detected(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _offset_type;
  _offset_type offset;

   typedef uint8_t _left_lane_detected_type;
  _left_lane_detected_type left_lane_detected;

   typedef uint8_t _right_lane_detected_type;
  _right_lane_detected_type right_lane_detected;





  typedef boost::shared_ptr< ::lane_follower::LaneDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lane_follower::LaneDetection_<ContainerAllocator> const> ConstPtr;

}; // struct LaneDetection_

typedef ::lane_follower::LaneDetection_<std::allocator<void> > LaneDetection;

typedef boost::shared_ptr< ::lane_follower::LaneDetection > LaneDetectionPtr;
typedef boost::shared_ptr< ::lane_follower::LaneDetection const> LaneDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lane_follower::LaneDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lane_follower::LaneDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lane_follower::LaneDetection_<ContainerAllocator1> & lhs, const ::lane_follower::LaneDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.offset == rhs.offset &&
    lhs.left_lane_detected == rhs.left_lane_detected &&
    lhs.right_lane_detected == rhs.right_lane_detected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lane_follower::LaneDetection_<ContainerAllocator1> & lhs, const ::lane_follower::LaneDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lane_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lane_follower::LaneDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_follower::LaneDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_follower::LaneDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_follower::LaneDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_follower::LaneDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_follower::LaneDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lane_follower::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a91f919b9ab61293532f56a60209641d";
  }

  static const char* value(const ::lane_follower::LaneDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa91f919b9ab61293ULL;
  static const uint64_t static_value2 = 0x532f56a60209641dULL;
};

template<class ContainerAllocator>
struct DataType< ::lane_follower::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lane_follower/LaneDetection";
  }

  static const char* value(const ::lane_follower::LaneDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lane_follower::LaneDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 offset\n"
"bool left_lane_detected\n"
"bool right_lane_detected\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lane_follower::LaneDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lane_follower::LaneDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.offset);
      stream.next(m.left_lane_detected);
      stream.next(m.right_lane_detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lane_follower::LaneDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lane_follower::LaneDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "offset: ";
    Printer<float>::stream(s, indent + "  ", v.offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_lane_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_lane_detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_lane_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_lane_detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANE_FOLLOWER_MESSAGE_LANEDETECTION_H
